import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import StyledComponentsRegistry from "@/lib/registry";
import { GlobalStyle } from "@/styles/Global.style";
import Header from "@/components/Header";
import NavContextProvider from "@/providers/NavProvider";
import MobileNav from "@/components/ui/MobileNav";
import LayoutInner from "@/components/LayoutInner";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Zenith Security Agency",
  description: "Generated by create next app",
  keywords: [],
  creator: "Osakwe Bonaventure Ifechukwu",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=switzer@300,400,500,600,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <StyledComponentsRegistry>
          <NavContextProvider>
            <LayoutInner> {children}</LayoutInner>
          </NavContextProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
